
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
# File: .github/workflows/repo-sync.yml

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: Clone Source Repo
      working-directory: /tmp
      env:
        # SOURCE_REPO: https://Christy99cc:${{ secrets.ACCESS_TOKEN }}@github.com/Christy99cc/blog.git
        # SOURCE_REPO_NAME: blog
        SOURCE_REPO: https://Christy99cc:${{ secrets.ACCESS_TOKEN }}@github.com/Christy99cc/Christy99cc.github.io.git
        SOURCE_REPO_NAME: Christy99cc.github.io
        SOURCE_BRANCH: master
        DESTINATION_REPO: https://Christy99cc:${{ secrets.ACCESS_TOKEN }}@github.com/Christy99cc/Christy99cc.github.io.git
        # DESTINATION_BRANCH: master
        DESTINATION_BRANCH: display
      run: |
        git config --global user.email "christy99cc@qq.com"
        git config --global user.name "Christy99cc"
        git clone $SOURCE_REPO && cd $SOURCE_REPO_NAME
        npm install && sudo npm install hexo -g
        hexo generate
        git remote set-url origin $DESTINATION_REPO && git add . && git commit -m "Update blog" && git push -f origin $DESTINATION_BRANCH
